apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-useraccount-config
  namespace: default
data:
  01-init-schema.sql: |
    -- MySQL Workbench Forward Engineering
    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

    -- Schema useraccount_db
    CREATE SCHEMA IF NOT EXISTS `useraccount_db` DEFAULT CHARACTER SET utf8 ;
    USE `useraccount_db` ;

    -- Table `useraccount_db`.`role`
    CREATE TABLE IF NOT EXISTS `useraccount_db`.`role` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `name` VARCHAR(45) NOT NULL,
      PRIMARY KEY (`id`))
    ENGINE = InnoDB;

    -- Table `useraccount_db`.`user`
    CREATE TABLE IF NOT EXISTS `useraccount_db`.`user` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `username` VARCHAR(50) NOT NULL,
      `email` VARCHAR(200) NOT NULL,
      `password` VARCHAR(500) NOT NULL,
      `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      `role_id` INT NOT NULL,
      PRIMARY KEY (`id`),
      INDEX `fk_User_Role1_idx` (`role_id` ASC) VISIBLE,
      UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
      UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
      CONSTRAINT `fk_User_Role1`
        FOREIGN KEY (`role_id`)
        REFERENCES `useraccount_db`.`role` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

    -- Table `useraccount_db`.`account`
    CREATE TABLE IF NOT EXISTS `useraccount_db`.`account` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `name` VARCHAR(100) NOT NULL,
      `amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
      `user_id` INT NOT NULL,
      PRIMARY KEY (`id`),
      INDEX `fk_Account_User_idx` (`user_id` ASC) VISIBLE,
      CONSTRAINT `fk_Account_User`
        FOREIGN KEY (`user_id`)
        REFERENCES `useraccount_db`.`user` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;